<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="assets/styles/facility.css" >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quantico&display=swap" rel="stylesheet"> 
    <link rel="icon" type="image/x-icon" href="assets/images/logo.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    
    <title>Classes</title>

  </head>
  <body>
    
      <style>
          .card-body{
              background: #000
          }
      </style>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

       <div class="container-fluid p-0" >
        
       
        <?php include('navbar.php') ?>
        
        <div class="row justify-content-center m-0">
            <div class="col-md-8">
                <div class="row justify-content-center my-3">
                    <div class="col-md-6">
                        <input type="search" class="form-control" id="search" placeholder="Buscar">

                    </div>
                </div>
                <div class="row justify-content-center mb-5" id="grid">

                    <div class="col-md-4 p-3" >
                        <div class="card grid-item" >
                            <img class="card-img-top" src="assets\images\fondo1.jpg" alt="Card image cap">
                            <div class="card-body">
                                <div class="row justify-content-center">
                                    <h5 class="card-title text-white">Clases de futbol Mañanas</h5>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 p-3" >
                        <div class="card grid-item" >
                            <img class="card-img-top" src="assets\images\fondo1.jpg" alt="Card image cap">
                            <div class="card-body">
                                <div class="row justify-content-center">
                                    <h5 class="card-title text-white">Clases de futbol Tardes</h5>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 p-3" >
                        <div class="card grid-item">
                            <img class="card-img-top" src="assets\images\fondo1.jpg" alt="Card image cap">
                            <div class="card-body">
                                <div class="row justify-content-center">
                                    <h5 class="card-title text-white">Clases de futbol Noches</h5>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                </div>
            </div>
        </div>
 
       
        

    </div>
    
    
  </body>
</html>
